In [1]:
#Importing pandas to load csv into dataframe.
import pandas as pd

In [2]:
#This is our final dataframe of malign comment classification.
df=pd.read_csv("testclassification.csv")

In [3]:
df

,Unnamed: 0,id,comment_text,length_of_words,clean_length_of_words,Bad Comments
0,0,00001cee341fdb12,yo bitch ja rule succesful ever whats hating s...,367,249,1
1,1,0000247867823ef7,rfc title fine is imo,50,29,0
2,2,00013b17ad220c46,source zawe ashton lapland,54,34,0
3,3,00017563c3f7919a,if look back source information updated correc...,205,117,0
4,4,00017695ad8997eb,anonymously edit article all,41,29,0
...,...,...,...,...,...,...
153159,153159,fffcd0960ee309b5,totally agree stuff nothing too long crap,60,42,1
153160,153160,fffd7a9a6eb32c16,throw field home plate get faster throwing cut...,198,117,0
153161,153161,fffda9e8d6fafa9e,okinotorishima category see change agree more ...,423,293,0
153162,153162,fffe8f1340a79fc2,one founding nation eu germany law return quit...,502,358,0
153163,153163,ffffce3fb183ee80,stop already bullshit welcome here i m fool th...,141,95,1

In [4]:
df= df.drop(['Unnamed: 0'], axis=1)

In [5]:
df

,id,comment_text,length_of_words,clean_length_of_words,Bad Comments
0,00001cee341fdb12,yo bitch ja rule succesful ever whats hating s...,367,249,1
1,0000247867823ef7,rfc title fine is imo,50,29,0
2,00013b17ad220c46,source zawe ashton lapland,54,34,0
3,00017563c3f7919a,if look back source information updated correc...,205,117,0
4,00017695ad8997eb,anonymously edit article all,41,29,0
...,...,...,...,...,...
153159,fffcd0960ee309b5,totally agree stuff nothing too long crap,60,42,1
153160,fffd7a9a6eb32c16,throw field home plate get faster throwing cut...,198,117,0
153161,fffda9e8d6fafa9e,okinotorishima category see change agree more ...,423,293,0
153162,fffe8f1340a79fc2,one founding nation eu germany law return quit...,502,358,0
153163,ffffce3fb183ee80,stop already bullshit welcome here i m fool th...,141,95,1